format_version: 10
pipelines:
  Parameterstorecreate:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/SpandanaThanuku/aws-ssm-parameters
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Apply:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init"]
                - exec:
                    command: terraform
                    arguments: [ "apply","-auto-approve" ]

